-- Insert 25 more seed data into url_usernames table
INSERT INTO url_usernames (username, url, password, category, organization_id)
VALUES 
    ('user1@example.com', 'www.shop1.com', 'pass123', 'shopping', 1),
    ('user2@example.com', 'www.shop2.com', 'pass123', 'shopping', 1),
    ('user3@example.com', 'www.shop3.com', 'pass123', 'shopping', 1),
    ('user4@example.com', 'www.work1.com', 'pass123', 'work', 1),
    ('user5@example.com', 'www.work2.com', 'pass123', 'work', 1),
    ('user6@example.com', 'www.work3.com', 'pass123', 'work', 1),
    ('user7@example.com', 'www.entertainment1.com', 'pass123', 'entertainment', 2),
    ('user8@example.com', 'www.entertainment2.com', 'pass123', 'entertainment', 2),
    ('user9@example.com', 'www.entertainment3.com', 'pass123', 'entertainment', 2),
    ('user10@example.com', 'www.social1.com', 'pass123', 'social', 2),
    ('user11@example.com', 'www.social2.com', 'pass123', 'social', 2),
    ('user12@example.com', 'www.social3.com', 'pass123', 'social', 2),
    ('user13@example.com', 'www.shopping4.com', 'pass123', 'shopping', 1),
    ('user14@example.com', 'www.shopping5.com', 'pass123', 'shopping', 1),
    ('user15@example.com', 'www.shopping6.com', 'pass123', 'shopping', 1),
    ('user16@example.com', 'www.work4.com', 'pass123', 'work', 1),
    ('user17@example.com', 'www.work5.com', 'pass123', 'work', 1),
    ('user18@example.com', 'www.work6.com', 'pass123', 'work', 1),
    ('user19@example.com', 'www.entertainment4.com', 'pass123', 'entertainment', 2),
    ('user20@example.com', 'www.entertainment5.com', 'pass123', 'entertainment', 2),
    ('user21@example.com', 'www.entertainment6.com', 'pass123', 'entertainment', 2),
    ('user22@example.com', 'www.social4.com', 'pass123', 'social', 2),
    ('user23@example.com', 'www.social5.com', 'pass123', 'social', 2),
    ('user24@example.com', 'www.social6.com', 'pass123', 'social', 2),
    ('user25@example.com', 'www.shopping7.com', 'pass123', 'shopping', 1),
    ('user26@example.com', 'www.shopping8.com', 'pass123', 'shopping', 1),
    ('user27@example.com', 'www.shopping9.com', 'pass123', 'shopping', 1),
    ('user28@example.com', 'www.work7.com', 'pass123', 'work', 1),
    ('user29@example.com', 'www.work8.com', 'pass123', 'work', 1),
    ('user30@example.com', 'www.work9.com', 'pass123', 'work', 1);
