INSERT INTO url_usernames (username, password, organization_id, url)
VALUES ('bobsmith@gmail.com','qwe123', 1, 'www.amazon.com')
INSERT INTO url_usernames (username, password, organization_id, url)
VALUES ('test2@gmail.com','qwe123', 1, 'www.gmail.com')
INSERT INTO url_usernames (username, password, organization_id, url)
VALUES ('test3@gmail.com','qwe123', 2, 'www.youtube.com')
INSERT INTO url_usernames (username, password, organization_id, url)
VALUES ('test4@gmail.com','qwe123', 2, 'www.x.com')
